/**
 * Just a stub to show intent, but sub in any production quality platform
 * event based logger
 */
public inherited sharing class LoggerService {

    public void error(String label, Exception e) {

    }

    public void error(String label, Exception e, Map<String, Object> toLog) {

    }

    public void info(String label, Map<String, Object> toLog) {

    }

    public void warn(String label, Map<String, Object> toLog) {
        
    }
}